### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by shiv6891** [marcocor/wikipedia-idf#4]
Getting the following error after completing almost all the articles 

`Traceback (most recent call last):
  File "wikipediaidf.py", line 113, in <module>
    sys.exit(main())
  File "wikipediaidf.py", line 81, in main
    for tokens, stems, t_to_s_mapping in pool.imap_unordered(process_line, get_lines(args.input)):
  File "/home/shivams/anaconda3/envs/mmf/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
EOFError: Compressed file ended before the end-of-stream marker was reached
`
I think I have extracted the bz2 file contents correctly.
Any help please?

**Comment by mhd0528** [comment]
Hi, have you solved this problem? I tried to download the dump file again but it doesn't work. I'm checking on the bz2 generated by the extractor but still haven't found anything yet.
